2019-06-24 10:31:58.224 +03:00 [INF] You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
2019-06-24 10:31:58.255 +03:00 [INF] Using the default authentication scheme Identity.Application for IdentityServer
2019-06-24 10:31:58.258 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for authentication
2019-06-24 10:31:58.258 +03:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-in
2019-06-24 10:31:58.259 +03:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-out
2019-06-24 10:31:58.259 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for challenge
2019-06-24 10:31:58.260 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for forbid
2019-06-24 10:31:59.071 +03:00 [DBG] Login Url: /Account/Login
2019-06-24 10:31:59.073 +03:00 [DBG] Login Return Url Parameter: ReturnUrl
2019-06-24 10:31:59.074 +03:00 [DBG] Logout Url: /Account/Logout
2019-06-24 10:31:59.075 +03:00 [DBG] ConsentUrl Url: /consent
2019-06-24 10:31:59.076 +03:00 [DBG] Consent Return Url Parameter: returnUrl
2019-06-24 10:31:59.076 +03:00 [DBG] Error Url: /home/error
2019-06-24 10:31:59.077 +03:00 [DBG] Error Id Parameter: errorId
2019-06-24 10:32:03.952 +03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2019-06-24 10:32:23.477 +03:00 [DBG] CORS request made for path: /Account/Login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2019-06-24 10:32:23.853 +03:00 [ERR] An error occurred using the connection to database 'Identity database' on server 'localhost'.
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
ClientConnectionId:1edf1128-a732-42b0-b935-9bc06be37c70
Error Number:4060,State:1,Class:11
2019-06-24 10:32:23.920 +03:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerAspNetIdentity.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:1edf1128-a732-42b0-b935-9bc06be37c70
Error Number:4060,State:1,Class:11
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:1edf1128-a732-42b0-b935-9bc06be37c70
Error Number:4060,State:1,Class:11
2019-06-24 10:32:23.961 +03:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerAspNetIdentity.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:1edf1128-a732-42b0-b935-9bc06be37c70
Error Number:4060,State:1,Class:11
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:1edf1128-a732-42b0-b935-9bc06be37c70
Error Number:4060,State:1,Class:11
2019-07-08 14:41:44.674 +03:00 [INF] You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
2019-07-08 14:41:44.711 +03:00 [INF] Using the default authentication scheme Identity.Application for IdentityServer
2019-07-08 14:41:44.714 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for authentication
2019-07-08 14:41:44.714 +03:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-in
2019-07-08 14:41:44.715 +03:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-out
2019-07-08 14:41:44.715 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for challenge
2019-07-08 14:41:44.716 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for forbid
2019-07-08 14:41:45.108 +03:00 [DBG] Login Url: /Account/Login
2019-07-08 14:41:45.111 +03:00 [DBG] Login Return Url Parameter: ReturnUrl
2019-07-08 14:41:45.112 +03:00 [DBG] Logout Url: /Account/Logout
2019-07-08 14:41:45.113 +03:00 [DBG] ConsentUrl Url: /consent
2019-07-08 14:41:45.114 +03:00 [DBG] Consent Return Url Parameter: returnUrl
2019-07-08 14:41:45.114 +03:00 [DBG] Error Url: /home/error
2019-07-08 14:41:45.115 +03:00 [DBG] Error Id Parameter: errorId
2019-07-08 14:42:12.780 +03:00 [INF] AuthenticationScheme: Identity.Application was challenged.
2019-07-09 15:25:31.086 +03:00 [INF] You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
2019-07-09 15:25:31.132 +03:00 [INF] Using the default authentication scheme Identity.Application for IdentityServer
2019-07-09 15:25:31.136 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for authentication
2019-07-09 15:25:31.136 +03:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-in
2019-07-09 15:25:31.137 +03:00 [DBG] Using Identity.External as default ASP.NET Core scheme for sign-out
2019-07-09 15:25:31.137 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for challenge
2019-07-09 15:25:31.137 +03:00 [DBG] Using Identity.Application as default ASP.NET Core scheme for forbid
2019-07-09 15:25:31.541 +03:00 [DBG] Login Url: /Account/Login
2019-07-09 15:25:31.545 +03:00 [DBG] Login Return Url Parameter: ReturnUrl
2019-07-09 15:25:31.547 +03:00 [DBG] Logout Url: /Account/Logout
2019-07-09 15:25:31.550 +03:00 [DBG] ConsentUrl Url: /consent
2019-07-09 15:25:31.551 +03:00 [DBG] Consent Return Url Parameter: returnUrl
2019-07-09 15:25:31.552 +03:00 [DBG] Error Url: /home/error
2019-07-09 15:25:31.555 +03:00 [DBG] Error Id Parameter: errorId
2019-07-09 15:25:57.143 +03:00 [DBG] Request path /.well-known/openid-configuration matched to endpoint type Discovery
2019-07-09 15:25:57.237 +03:00 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
2019-07-09 15:25:57.239 +03:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
2019-07-09 15:25:57.244 +03:00 [DBG] Start discovery request
2019-07-09 15:25:57.350 +03:00 [DBG] Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
2019-07-09 15:25:57.354 +03:00 [DBG] Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryKeyEndpoint
2019-07-09 15:25:57.355 +03:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
2019-07-09 15:25:57.360 +03:00 [DBG] Start key discovery request
2019-07-09 15:25:57.405 +03:00 [DBG] Request path /connect/authorize matched to endpoint type Authorize
2019-07-09 15:25:57.409 +03:00 [DBG] Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeEndpoint
2019-07-09 15:25:57.410 +03:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
2019-07-09 15:25:57.414 +03:00 [DBG] Start authorize request
2019-07-09 15:25:57.421 +03:00 [DBG] No user present in authorize request
2019-07-09 15:25:57.425 +03:00 [DBG] Start authorize request protocol validation
2019-07-09 15:25:57.439 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:25:57.444 +03:00 [DBG] Checking for PKCE parameters
2019-07-09 15:25:57.446 +03:00 [DBG] No PKCE used.
2019-07-09 15:25:57.472 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-07-09 15:25:57.486 +03:00 [INF] ValidatedAuthorizeRequest
{"ClientId":"mvc","ClientName":"MVC Client","RedirectUri":"http://localhost:5002/signin-oidc","AllowedRedirectUris":["http://localhost:5002/signin-oidc"],"SubjectId":"anonymous","ResponseType":"code id_token","ResponseMode":"form_post","GrantType":"hybrid","RequestedScopes":"openid profile api1 offline_access","State":"CfDJ8Dh4-9r02NNHj0Qss8x5z1gwfWRG2yeX7l1T0O4-P8c9XaItZjdt1t9c_HkcKh8Cnvs_6XIyAFVTbULnuLlT7dsozkz-uAzX9PAOyPIx-fuf3FD-XVVxDeir4qKyYUZs2HK78wt8Z5w_wn_TdC_EUQUy9PwuTfF8q_oHNf4J3SaAOujCvQyXnOQk7W8fEOhvz2nXwUN-PuabyHh0FEV41r7kJUEweUhFFsuEfBDVJj-Z6Mr9-XSTGFayzqImCBdSfns-VztZNxRPAl_R9VSUCiUFvuiN5X8tKniZJtTUiQiQQp-mwPg2OGgqiXjytoLyUw","UiLocales":null,"Nonce":"636982719573850612.YWI5ZGRlOGUtNWU2NS00YjQ2LWI2MjctMmQwYWFlMjkyYjNhZjBmYWRkMDAtMWQwMi00MWQ4LTk5ODctYjI2ZGYyNDFmMThm","AuthenticationContextReferenceClasses":null,"DisplayMode":null,"PromptMode":null,"MaxAge":null,"LoginHint":null,"SessionId":null,"Raw":{"client_id":"mvc","redirect_uri":"http://localhost:5002/signin-oidc","response_type":"code id_token","scope":"openid profile api1 offline_access","response_mode":"form_post","nonce":"636982719573850612.YWI5ZGRlOGUtNWU2NS00YjQ2LWI2MjctMmQwYWFlMjkyYjNhZjBmYWRkMDAtMWQwMi00MWQ4LTk5ODctYjI2ZGYyNDFmMThm","state":"CfDJ8Dh4-9r02NNHj0Qss8x5z1gwfWRG2yeX7l1T0O4-P8c9XaItZjdt1t9c_HkcKh8Cnvs_6XIyAFVTbULnuLlT7dsozkz-uAzX9PAOyPIx-fuf3FD-XVVxDeir4qKyYUZs2HK78wt8Z5w_wn_TdC_EUQUy9PwuTfF8q_oHNf4J3SaAOujCvQyXnOQk7W8fEOhvz2nXwUN-PuabyHh0FEV41r7kJUEweUhFFsuEfBDVJj-Z6Mr9-XSTGFayzqImCBdSfns-VztZNxRPAl_R9VSUCiUFvuiN5X8tKniZJtTUiQiQQp-mwPg2OGgqiXjytoLyUw","x-client-SKU":"ID_NETSTANDARD2_0","x-client-ver":"5.3.0.0"},"$type":"AuthorizeRequestValidationLog"}
2019-07-09 15:25:57.517 +03:00 [INF] Showing login: User is not authenticated
2019-07-09 15:25:57.558 +03:00 [DBG] Start authorize request protocol validation
2019-07-09 15:25:57.559 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:25:57.561 +03:00 [DBG] Checking for PKCE parameters
2019-07-09 15:25:57.562 +03:00 [DBG] No PKCE used.
2019-07-09 15:25:57.563 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-07-09 15:25:57.567 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:26:52.101 +03:00 [DBG] CORS request made for path: /Account/Login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
2019-07-09 15:26:52.131 +03:00 [DBG] Start authorize request protocol validation
2019-07-09 15:26:52.132 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:26:52.135 +03:00 [DBG] Checking for PKCE parameters
2019-07-09 15:26:52.136 +03:00 [DBG] No PKCE used.
2019-07-09 15:26:52.137 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-07-09 15:26:52.418 +03:00 [ERR] An error occurred using the connection to database 'Identity database' on server 'localhost'.
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
ClientConnectionId:c7f3684b-8af1-415a-88e6-3cd09c991af4
Error Number:4060,State:1,Class:11
2019-07-09 15:26:52.472 +03:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerAspNetIdentity.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:c7f3684b-8af1-415a-88e6-3cd09c991af4
Error Number:4060,State:1,Class:11
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
ClientConnectionId:c7f3684b-8af1-415a-88e6-3cd09c991af4
Error Number:4060,State:1,Class:11
2019-07-09 15:26:52.505 +03:00 [ERR] An exception occurred in the database while iterating the results of a query for context type 'IdentityServerAspNetIdentity.Data.ApplicationDbContext'.
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:c7f3684b-8af1-415a-88e6-3cd09c991af4
Error Number:4060,State:1,Class:11
System.Data.SqlClient.SqlException (0x80131904): Не удается открыть базу данных "Identity database", запрашиваемую именем входа. Не удалось выполнить вход.
При входе в систему пользователя "WIN-A518R1T7NMM\admin" произошла ошибка.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
ClientConnectionId:c7f3684b-8af1-415a-88e6-3cd09c991af4
Error Number:4060,State:1,Class:11
2019-07-09 15:27:14.128 +03:00 [DBG] Request path /connect/authorize matched to endpoint type Authorize
2019-07-09 15:27:14.131 +03:00 [DBG] Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeEndpoint
2019-07-09 15:27:14.134 +03:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
2019-07-09 15:27:14.136 +03:00 [DBG] Start authorize request
2019-07-09 15:27:14.137 +03:00 [DBG] No user present in authorize request
2019-07-09 15:27:14.138 +03:00 [DBG] Start authorize request protocol validation
2019-07-09 15:27:14.140 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:27:14.141 +03:00 [DBG] Checking for PKCE parameters
2019-07-09 15:27:14.142 +03:00 [DBG] No PKCE used.
2019-07-09 15:27:14.143 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-07-09 15:27:14.144 +03:00 [INF] ValidatedAuthorizeRequest
{"ClientId":"mvc","ClientName":"MVC Client","RedirectUri":"http://localhost:5002/signin-oidc","AllowedRedirectUris":["http://localhost:5002/signin-oidc"],"SubjectId":"anonymous","ResponseType":"code id_token","ResponseMode":"form_post","GrantType":"hybrid","RequestedScopes":"openid profile api1 offline_access","State":"CfDJ8Dh4-9r02NNHj0Qss8x5z1hZYTgm6vujqKoY-FEXwKjed4584ijPJMAj8syg-mONX5wHkmyMnUz4ruAtFc7Dki4NLeBnKDUj-1lJR80UOkcGNHZ7FKuUFaMu7JXQ2Dj6G0gttSgLZl0YB2o4e6UgGJI3ScDm4K7H_ACuyy8yiPm9XsT6bToFJXgEMkFOErlWNLg0H-vGxIYH0d14jjQP5gV36alAjWwWxRdxkfRx2-OHQVGeBO3wLfT39pLNu1h1PEOiSDpXqb7waUTPI6_Cfk9kchbp0WwUnmYBXTkWwJsl4DkGh0FyGfCWDd3Ow7qAeg","UiLocales":null,"Nonce":"636982720341240357.MDliNjEzZjEtZmE5Yi00ODk1LTkwNzgtYTEzYmRiZGQ0N2Y2MWYyMDk4MDAtMWUyOS00MzdiLTkyNTMtOTJiODNkMzRkMzg0","AuthenticationContextReferenceClasses":null,"DisplayMode":null,"PromptMode":null,"MaxAge":null,"LoginHint":null,"SessionId":null,"Raw":{"client_id":"mvc","redirect_uri":"http://localhost:5002/signin-oidc","response_type":"code id_token","scope":"openid profile api1 offline_access","response_mode":"form_post","nonce":"636982720341240357.MDliNjEzZjEtZmE5Yi00ODk1LTkwNzgtYTEzYmRiZGQ0N2Y2MWYyMDk4MDAtMWUyOS00MzdiLTkyNTMtOTJiODNkMzRkMzg0","state":"CfDJ8Dh4-9r02NNHj0Qss8x5z1hZYTgm6vujqKoY-FEXwKjed4584ijPJMAj8syg-mONX5wHkmyMnUz4ruAtFc7Dki4NLeBnKDUj-1lJR80UOkcGNHZ7FKuUFaMu7JXQ2Dj6G0gttSgLZl0YB2o4e6UgGJI3ScDm4K7H_ACuyy8yiPm9XsT6bToFJXgEMkFOErlWNLg0H-vGxIYH0d14jjQP5gV36alAjWwWxRdxkfRx2-OHQVGeBO3wLfT39pLNu1h1PEOiSDpXqb7waUTPI6_Cfk9kchbp0WwUnmYBXTkWwJsl4DkGh0FyGfCWDd3Ow7qAeg","x-client-SKU":"ID_NETSTANDARD2_0","x-client-ver":"5.3.0.0"},"$type":"AuthorizeRequestValidationLog"}
2019-07-09 15:27:14.160 +03:00 [INF] Showing login: User is not authenticated
2019-07-09 15:27:14.165 +03:00 [DBG] Start authorize request protocol validation
2019-07-09 15:27:14.166 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:27:14.168 +03:00 [DBG] Checking for PKCE parameters
2019-07-09 15:27:14.170 +03:00 [DBG] No PKCE used.
2019-07-09 15:27:14.171 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-07-09 15:27:14.174 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:27:28.165 +03:00 [DBG] Request path /connect/authorize matched to endpoint type Authorize
2019-07-09 15:27:28.169 +03:00 [DBG] Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeEndpoint
2019-07-09 15:27:28.172 +03:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
2019-07-09 15:27:28.175 +03:00 [DBG] Start authorize request
2019-07-09 15:27:28.177 +03:00 [DBG] No user present in authorize request
2019-07-09 15:27:28.178 +03:00 [DBG] Start authorize request protocol validation
2019-07-09 15:27:28.179 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:27:28.180 +03:00 [DBG] Checking for PKCE parameters
2019-07-09 15:27:28.182 +03:00 [DBG] No PKCE used.
2019-07-09 15:27:28.183 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-07-09 15:27:28.185 +03:00 [INF] ValidatedAuthorizeRequest
{"ClientId":"mvc","ClientName":"MVC Client","RedirectUri":"http://localhost:5002/signin-oidc","AllowedRedirectUris":["http://localhost:5002/signin-oidc"],"SubjectId":"anonymous","ResponseType":"code id_token","ResponseMode":"form_post","GrantType":"hybrid","RequestedScopes":"openid profile api1 offline_access","State":"CfDJ8Dh4-9r02NNHj0Qss8x5z1iz3bWbteZIWhGxZGziB4C9bIHtegP95gsx8cgBiomMHFsJ59OSzTKbCZkd7DtHMBi18NGpxHdlWlKcTTWu3Sf1Gt43HVFSy-u-0EGQKrs0AQu5BW0kKiWjaiXyC55HW_oqgWKkV9kwr4qBcrk7-fdMR27pAjDEnoUz0RQTDBjrnF7Zd2b4NLfpdn77bx30o9dGDkMENq-RTWoo3i9G69Pd9Hz29vFiZojbZ957C1cwDPuH0ubEtbZjRvoimAfpBlKcyJMVBD7lzPdIIjt6FgCiiqmxf0HJI8qNUNgkkLnSnA","UiLocales":null,"Nonce":"636982720481622851.Nzg0MTYzNjUtYWUzNi00NDQ3LTk3MjItYTcwYjE0Njk2ZmJiYjEyMjgzYTctNWM0Yi00YTcxLThhZjgtN2VlOTVjYzI1YTc5","AuthenticationContextReferenceClasses":null,"DisplayMode":null,"PromptMode":null,"MaxAge":null,"LoginHint":null,"SessionId":null,"Raw":{"client_id":"mvc","redirect_uri":"http://localhost:5002/signin-oidc","response_type":"code id_token","scope":"openid profile api1 offline_access","response_mode":"form_post","nonce":"636982720481622851.Nzg0MTYzNjUtYWUzNi00NDQ3LTk3MjItYTcwYjE0Njk2ZmJiYjEyMjgzYTctNWM0Yi00YTcxLThhZjgtN2VlOTVjYzI1YTc5","state":"CfDJ8Dh4-9r02NNHj0Qss8x5z1iz3bWbteZIWhGxZGziB4C9bIHtegP95gsx8cgBiomMHFsJ59OSzTKbCZkd7DtHMBi18NGpxHdlWlKcTTWu3Sf1Gt43HVFSy-u-0EGQKrs0AQu5BW0kKiWjaiXyC55HW_oqgWKkV9kwr4qBcrk7-fdMR27pAjDEnoUz0RQTDBjrnF7Zd2b4NLfpdn77bx30o9dGDkMENq-RTWoo3i9G69Pd9Hz29vFiZojbZ957C1cwDPuH0ubEtbZjRvoimAfpBlKcyJMVBD7lzPdIIjt6FgCiiqmxf0HJI8qNUNgkkLnSnA","x-client-SKU":"ID_NETSTANDARD2_0","x-client-ver":"5.3.0.0"},"$type":"AuthorizeRequestValidationLog"}
2019-07-09 15:27:28.202 +03:00 [INF] Showing login: User is not authenticated
2019-07-09 15:27:28.205 +03:00 [DBG] Start authorize request protocol validation
2019-07-09 15:27:28.205 +03:00 [DBG] client configuration validation for client mvc succeeded.
2019-07-09 15:27:28.206 +03:00 [DBG] Checking for PKCE parameters
2019-07-09 15:27:28.207 +03:00 [DBG] No PKCE used.
2019-07-09 15:27:28.208 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-07-09 15:27:28.210 +03:00 [DBG] client configuration validation for client mvc succeeded.
